### ISSUE TITLE
[NEW SETUP] Docker instances consistently restarting

### ISSUE THREAD

**Issue by dickiesanders** [b-m-f/WirtBot#161]
@b-m-f  - Per our last thread, I blew away my existing setup and followed the updated [setup guide](https://wirtbot.com/documentation/setup.html#dependencies). 

After creating my docker-compose.yml file and running `docker-compose -d up && docker logs -f WirtBot` I see several errors, see screenshot, and the containers continually restart. In addition to the container errors, I'm seeing odd permission issues where the user "lxd" and group "998" are used for my wiregaurd and data directories. 

I have the following dependencies met:
 - Linux kernel > 5.6  (**5.6.0-050600-generic**) **On Ubuntu 20.04.2**
 - Docker (**docker.io/focal-updates,now 19.03.8-0ubuntu1.20.04.2 amd64 [installed]**)
 - Docker-compose (**docker-compose/focal,now 1.25.0-1 all [installed]**)

Docker-compose.yml:
```version: "3.4"

services:
  WirtBot:
    image: bmff/wirtbot
    network_mode: host
    container_name: WirtBot
    ports:
      - 80:80
      - 3030:3030
      - 10101:10101/udp
    restart: "unless-stopped"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./wireguard:/etc/wireguard
      - ./data:/dns
    environment:
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
      - "PORT=3030"
      - "MANAGED_DNS_ENABLED=1"
      - "MANAGED_DNS_DEVICE_FILE=/dns/Corefile"
      - "CONFIG_PATH=/etc/wireguard/server.conf"
  coredns:
    network_mode: host
    image: coredns/coredns
    container_name: WirtBotDNS
    ports:
      - 53:53/udp
    restart: "unless-stopped"
    working_dir: /v
    volumes:
      - ./data:/v
```

Screenshot(s):
-Container errors:
![wirtbot-fail](https://user-images.githubusercontent.com/12834880/108120520-626e2b00-706f-11eb-8ed8-cf7c119b6f2c.png)

- Permissions issues:
![permissions](https://user-images.githubusercontent.com/12834880/108120627-91849c80-706f-11eb-8221-95585772ae7c.png)

**note: I'm fairly certain that using "network_mode: host" overrides the "ports" directive in the docker-compose.yaml file, so this is causing the CoreDNS container to collide w/ the host OS DNS process listening on port 53.**

**Comment by b-m-f** [comment]
@dickiesanders thanks for all the details.
Sorry it didn't work for you straight away.

I'll have to do some digging on this and will come back to you!

**Comment by b-m-f** [comment]
And one more question.

Are you running this on a clean VM/VPS?

**Comment by dickiesanders** [comment]
@b-m-f - yes, I am running the setup on a clean Ubuntu 20.04.2 install with these four post install steps:

- apt update && apt upgrade -y
- install latest 5.6 kernel
- apt install -y docker.io
- apt install -y docker-compose

(All ran with sudo)

**Comment by b-m-f** [comment]
Thanks. I will spin up the same setup and try to get a fix out.

I suspect that one of the culprits is the user generation in the Dockerfile.

**Comment by b-m-f** [comment]
Hi @dickiesanders,

A little update:

## Port 53

This is correct, it will be overwritten with `networkmode: host` and without. Rather, it will fail on Ubuntu as `systemd-resolved` already binds to 53. 

If the main DNS from the machine is to be used than the WirtBot can be run without DNS capabilities.


## 998 User?

This one is probably due to the fact that 2 users are being created inside the Docker container. 
These users are given permissions onto a certain set of files that are necessary for the programs they run.

This is done using the s6-overlay.

I will look at other Open Source project over the weekend and probably provide 2 Variables to the Image where the UIDs:GIDs can be set from the outside to avoid clashing with existing users on a machine.

## Rust crashing

This one still completely baffles me.

Could you tell me what exactly you did on the interface for this to crash?

Some code from the **CORS** filters of https://github.com/seanmonstar/warp is crashing and Id have to understand exactly what triggers this. 


Thanks for all the info and Ill let you know as soon as I have it all fixed :)

**Comment by b-m-f** [comment]
@dickiesanders 

## Container crash
The problem is here:
```
   - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
```
Make sure to specify the Protocol, most likely `http://`

This should make sure you can get started without crashes

## Users

I will push a new version later today that fixes this.
